# Generated by Django 2.2 on 2020-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('link_man', models.CharField(max_length=10, verbose_name='联系人')),
                ('link_tel', models.CharField(max_length=12, verbose_name='联系电话')),
                ('delivery_day', models.DateTimeField(max_length=128, verbose_name='交货时间')),
                ('delivery_site', models.CharField(max_length=128, verbose_name='交货地址')),
            ],
            options={
                'verbose_name': '客户表',
                'db_table': 'client_info',
            },
        ),
    ]
