# Generated by Django 2.2 on 2020-10-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='clientInfo',
        ),
    ]
