# Generated by Django 2.2 on 2020-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0002_auto_20201008_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='uid',
            field=models.IntegerField(default=10),
        ),
    ]
