# Generated by Django 2.2 on 2020-10-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0003_clientinfo_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='delivery_day',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='delivery_site',
        ),
    ]
