# Generated by Django 2.2 on 2020-10-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0004_auto_20201018_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='key',
            field=models.IntegerField(auto_created=True, default=10000),
        ),
    ]
