# Generated by Django 2.2 on 2020-10-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0005_clientinfo_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='key',
            field=models.IntegerField(auto_created=True, blank=True, db_column='c_key', verbose_name='商品号'),
        ),
    ]
