# Generated by Django 2.2 on 2020-10-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0006_auto_20201018_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='key',
            field=models.IntegerField(auto_created=True, blank=True, verbose_name='商品号'),
        ),
    ]
