# Generated by Django 2.2 on 2020-10-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0007_auto_20201018_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='key',
            field=models.IntegerField(auto_created=True),
        ),
    ]
