# Generated by Django 2.2 on 2020-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0008_auto_20201018_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='key',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
