# Generated by Django 2.2 on 2020-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0009_auto_20201018_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplierInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(auto_created=True, default=1)),
                ('supplier_name', models.CharField(max_length=50, verbose_name='供应商名称')),
                ('link_man', models.CharField(max_length=10, verbose_name='联系人')),
                ('link_tel', models.CharField(max_length=12, verbose_name='联系电话')),
                ('uid', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': '供应商表',
                'db_table': 'supplier_info',
            },
        ),
    ]
