# Generated by Django 2.2 on 2020-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0010_supplierinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=10, verbose_name='标签名称')),
                ('uid', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': '标签类目表',
                'db_table': 'tabs_info',
            },
        ),
    ]
