# Generated by Django 2.2 on 2020-11-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0011_tabsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=10, verbose_name='商品名称')),
                ('remark', models.TextField(verbose_name='备注')),
                ('specification', models.CharField(max_length=20, verbose_name='规格/型号')),
                ('unit', models.CharField(max_length=5, verbose_name='单位')),
                ('sale_price', models.IntegerField(verbose_name='销售价格')),
                ('buy_price', models.IntegerField(verbose_name='采购价格')),
                ('uid', models.IntegerField(default=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('tab_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csmApp.tabsInfo')),
            ],
            options={
                'verbose_name': '商品表',
                'db_table': 'goods_info',
            },
        ),
    ]
