# Generated by Django 2.2 on 2020-11-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0013_auto_20201103_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='tab_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csmApp.tabsInfo', to_field='tab_name'),
        ),
        migrations.AlterField(
            model_name='tabsinfo',
            name='tab_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='标签名称'),
        ),
    ]
