# Generated by Django 2.2 on 2020-11-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0015_auto_20201105_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='client_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='tab_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csmApp.tabsInfo', to_field='tab_name', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='销售单号')),
                ('sale_date', models.DateField(verbose_name='销售日期')),
                ('delivery_site', models.CharField(max_length=100, verbose_name='交货地址')),
                ('delivery_date', models.DateField(verbose_name='交货日期')),
                ('total_price', models.FloatField(verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sale', models.CharField(blank=True, max_length=50, null=True, verbose_name='销售方')),
                ('sale_man', models.CharField(blank=True, max_length=50, null=True, verbose_name='销售员')),
                ('sale_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('uid', models.IntegerField(default=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csmApp.clientInfo', to_field='client_name', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单表',
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='orderGoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='销售单号')),
                ('sale_num', models.IntegerField(verbose_name='销售数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csmApp.goodsInfo', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单商品表',
                'db_table': 'orderGoods_info',
            },
        ),
    ]
