# Generated by Django 2.2 on 2020-11-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmApp', '0017_orderinfo_order_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_finish',
            field=models.BooleanField(default=False, verbose_name='订单完成状态'),
        ),
    ]
