# Generated by Django 2.2 on 2020-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User3',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('reqtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user3',
                'ordering': ['username'],
            },
        ),
    ]
